/**
 * A standalone bank of kitchen/cooking one-liners -- distinct from
 * ChefSprite/ChefSprite3D's own DEFAULT_LINES (which are in-character banter
 * about the chef's session/rendering/idle state). This is just actual jokes,
 * meant to be passed as `lines` to ChefMascot wherever a caller wants the
 * chef telling jokes instead of doing his usual bit.
 *
 * Replaced wholesale 2026-07-21 with the user's own batch (their prior
 * feedback: the previous 300-line bank was "dogshit"). The source list
 * arrived as plain text with mangled UTF-8 (e.g. "flambÃ©", "Iâve") from a
 * lossy copy/paste -- re-encoded here, not passed through literally. Several
 * of the source jokes were the same mad-lib template repeated with only the
 * ingredient swapped (e.g. ~30 near-identical "Kitchen Logic #N: caramelized/
 * flambé" lines, ~25 near-identical "Dating a chef is wild..." lines) --
 * kept one representative example of each template's funniest instance
 * rather than dozens of numbered/reworded duplicates, since a chef repeating
 * the same joke structure back-to-back reads as broken, not funny. Genuinely
 * distinct jokes/one-liners were kept as-is.
 */
export const KITCHEN_JOKES: string[] = [
  "Overheard in the back of house: The waiter just spilled the secret sauce. We are officially doomed.",
  "You know it's a bad dinner service when the sous chef looks at you and says, 'Well, at least it's cooked... mostly.'",
  "Kitchen Logic: If it smells like it's burning, it's 'caramelized'. If it's fully on fire, it's 'flambé'.",
  "When reading a recipe for egg: 'Serves 4' actually means 'Serves 1 hungry person and maybe a squirrel'.",
  "I think my stove is passive aggressive. It's always on the back burner.",
  "When reading a recipe for bread: 'Simmer gently' actually means 'boil violently while you scroll on your phone'.",
  "Kitchen Confession: I tried to have a serious talk with the pepper, but it is spicing things up.",
  "Dating a chef is wild. Last night they yelled at the grape because it's wine-ing.",
  "Never trust a sink on a Monday. It's usually plugged in.",
  "They say don't play with your food, but the water started it. I mean, it's going with the flow.",
  "Fake Yelp Review: Ordered the salad. Honestly, it's tossing ideas around. 3/5 stars.",
  "Kitchen Confession: I tried to have a serious talk with the mushroom, but it is taking up too much mush-room.",
  "Never trust a dishwasher on a Monday. It's usually drained.",
  "What's the difference between a pastry chef and a puppy? Eventually, the puppy stops whining when you give it food.",
  "They say don't play with your food, but the pasta started it. I mean, it's an impasta.",
  "Kitchen Confession: I tried to have a serious talk with the cheese, but it was acting a bit grated.",
  "I think my refrigerator is passive aggressive. It's always pretty cool.",
  "They say don't play with your food, but the lettuce started it. I mean, it's ahead of the game.",
  "Overheard in the back of house: The food critic just lost the Michelin star. We are officially doomed.",
  "I burned my Hawaiian pizza today. I guess I should have cooked it on aloha temperature.",
  "When reading a recipe for chicken: 'Let rest for 5 minutes' actually means 'eat immediately and burn the roof of your mouth'.",
  "They say don't play with your food, but the garlic started it. I mean, it's crushing it.",
  "You never realize how long a minute actually is until you're staring at the microwave with 0:00 on the clock waiting for the beep.",
  "Overheard in the back of house: The head chef just used margarine instead of butter. We are officially doomed.",
  "I've started telling everyone about the benefits of eating dried grapes. It's all about raisin awareness.",
  "Overheard in the back of house: The restaurant owner just ate half the inventory. We are officially doomed.",
  "Overheard in the back of house: The busboy just ate half the inventory. We are officially doomed.",
  "Roommate ad: Must be okay with my stove. It can be a little sizzling at times.",
  "Overheard in the back of house: The dishwasher just spilled the secret sauce. We are officially doomed.",
  "I think my oven is passive aggressive. It's always full of hot air.",
  "Dating a chef is wild. Last night they yelled at the apple because it's hardcore.",
  "Kitchen Confession: I tried to have a serious talk with the orange, but it is full of zest.",
  "Roommate ad: Must be okay with my coffee maker. It can be a little wired at times.",
  "If you want to feel important, just stand next to a boiling pot of pasta. It demands all your attention.",
  "My cooking is so fabulous even the smoke alarm cheers me on.",
  "Dating a chef is wild. Last night they yelled at the mushroom because it's a fun guy.",
  "Fake Yelp Review: Ordered the orange. Honestly, it's peeling the pressure. 3/5 stars.",
  "Kitchen Confession: I tried to have a serious talk with the butter, but it is melting down.",
  "Kitchen Confession: I tried to have a serious talk with the bacon, but it is bringing home the bacon.",
  "Overheard in the back of house: The bartender just ate half the inventory. We are officially doomed.",
  "Fake Yelp Review: Ordered the pepper. Honestly, it's a little salty. 3/5 stars.",
  "Never trust a toaster on a Monday. It's usually burnt out.",
  "They say don't play with your food, but the cake started it. I mean, it's a piece of cake.",
  "I think my dishwasher is passive aggressive. It's always washing its hands of this.",
  "I think my microwave is passive aggressive. It's always making waves.",
  "Never trust a freezer on a Monday. It's usually icy.",
  "Dating a chef is wild. Last night they yelled at the soup because it's souper.",
  "Never trust a blender on a Monday. It's usually mixed up.",
  "Fake Yelp Review: Ordered the cheese. Honestly, it's too gouda to be true. 3/5 stars.",
  "They say don't play with your food, but the banana started it. I mean, it's going bananas.",
  "Kitchen Confession: I tried to have a serious talk with the apple, but it is the apple of my eye.",
  "Roommate ad: Must be okay with my toaster. It can be a little burnt out at times.",
  "Dating a chef is wild. Last night they yelled at the chicken because it's winging it.",
  "Fake Yelp Review: Ate the chef's special soup. It was so bad, I almost called the broth-erhood to investigate.",
  "Dating a chef is wild. Last night they yelled at the milk because it's udderly ridiculous.",
  "Dating a chef is wild. Last night they yelled at the fish because it's a little fishy.",
  "You know it's a bad dinner service when the bartender looks at you and says, 'Well, at least it's cooked... mostly.'",
  "Fake Yelp Review: Ordered the lettuce. Honestly, it's ahead of the game. 3/5 stars.",
  "Kitchen Confession: I tried to have a serious talk with the grape, but it is doing a grape job.",
  "I'm on a seafood diet. I see food and I eat it. Classic, but it still slaps.",
  "Fake Yelp Review: Ordered the coffee. Honestly, it has a lot of grounds. 3/5 stars.",
  "Roommate ad: Must be okay with my microwave. It can be a little quick to heat up at times.",
  "Kitchen Confession: I tried to have a serious talk with the salad, but it is dressing up.",
  "Overheard in the back of house: The food critic just put pineapple on the staff meal pizza. We are officially doomed.",
  "They say don't play with your food, but the tomato started it. I mean, it needs to ketchup.",
  "When reading a recipe for garlic: 'Drizzle with olive oil' actually means 'drown it until the US military invades'.",
  "Overheard in the back of house: The dishwasher just burned the garlic. We are officially doomed.",
  "Kitchen Confession: I tried to have a serious talk with the banana, but it has split.",
  "When reading a recipe for carrot: 'A pinch of salt' actually means 'throw salt at it until your ancestors whisper to stop'.",
  "My toaster has two settings: 'Warm bread' and 'Active volcano'.",
  "I think my freezer is passive aggressive. It's always giving me the cold shoulder.",
  "Cooking rule #1: If at first you don't succeed, order pizza.",
  "I used to be a baker, but I lost interest. I just didn't make enough dough.",
  "Fake Yelp Review: Ordered the cookie. Honestly, that's how the cookie crumbles. 3/5 stars.",
  "Dating a chef is wild. Last night they yelled at the lemon because it's souring the mood.",
  "Overheard in the back of house: The waiter just called a customer 'bruh'. We are officially doomed.",
  "Kitchen Confession: I tried to have a serious talk with the coffee, but it is brewing up trouble.",
  "Kitchen Confession: I tried to have a serious talk with the lemon, but it is getting squeezed.",
  "I accidentally rubbed ketchup in my eyes. Now I have Heinz-sight.",
  "They say don't play with your food, but the pie started it. I mean, it has pie in the sky ideas.",
  "Fake Yelp Review: The new anti-gravity restaurant is okay. The food is great, but it has absolutely no atmosphere.",
  "Never trust a refrigerator on a Monday. It's usually chill.",
  "Overheard in the back of house: The sous chef just overcooked the risotto. We are officially doomed.",
  "Kitchen Confession: I tried to have a serious talk with the lettuce, but it needs to lettuce be.",
  "Fake Yelp Review: Ordered the potato. Honestly, it's a dictator. 3/5 stars.",
  "Never trust a microwave on a Monday. It's usually quick to heat up.",
  "Kitchen Confession: I tried to have a serious talk with the bread, but it keeps loafing around.",
  "Trying to eat healthy is just pretending to like salads until you die.",
  "Overheard in the back of house: The busboy just called a customer 'bruh'. We are officially doomed.",
  "Kitchen Confession: I tried to have a serious talk with the potato, but it is peeling good.",
  "Kitchen Confession: I tried to have a serious talk with the chicken, but it is totally plucked.",
  "Roommate ad: Must be okay with my blender. It can be a little mixed up at times.",
  "Overheard in the back of house: The waiter just overcooked the risotto. We are officially doomed.",
  "When reading a recipe for lemon: 'Serves 4' actually means 'Serves 1 hungry person and maybe a squirrel'.",
  "Fake Yelp Review: Ordered the bread. Honestly, it's on a roll. 3/5 stars.",
  "When a recipe calls for '1 clove of garlic', what they actually mean is '1 bulb'.",
  "Never trust a coffee maker on a Monday. It's usually wired.",
  "My chef friend just got fired for stealing. He was caught taking a whisk.",
  "Roommate ad: Must be okay with my refrigerator. It can be a little chill at times.",
  "I have a lot of jokes about unemployed chefs, but none of them work.",
  "Overheard in the back of house: The bartender just burned the garlic. We are officially doomed.",
  "Roommate ad: Must be okay with my oven. It can be a little baked at times.",
  "Overheard in the back of house: The line cook just yelled at the host. We are officially doomed.",
  "Fake Yelp Review: Ordered the soup. Honestly, it's souper. 3/5 stars.",
  "A boiled egg every morning is hard to beat.",
  "I ordered a chicken and an egg from Amazon. I'll let you know what comes first.",
  "Fake Yelp Review: Ordered the steak. Honestly, the stakes are high. 3/5 stars.",
  "Overheard in the back of house: The busboy just microwaved the wagyu. We are officially doomed.",
  "Overheard in the back of house: The restaurant owner just dropped the prime rib. We are officially doomed.",
  "I put my root beer in a square glass. Now it's just beer.",
  "Kitchen Confession: I tried to have a serious talk with the tomato, but it is seeing red.",
  "Overheard in the back of house: The sous chef just spilled the secret sauce. We are officially doomed.",
  "My wife asked me to sync the calendar. So I washed all the colanders in the kitchen. She is not amused.",
  "I'm reading a book on the history of butter. It's a fascinating spread.",
  "Kitchen Confession: I tried to have a serious talk with the egg, but it is cracking up.",
  "Roommate ad: Must be okay with my dishwasher. It can be a little drained at times.",
  "Overheard in the back of house: The line cook just tried to deglaze a pan with tap water. We are officially doomed.",
  "Kitchen Confession: I tried to have a serious talk with the pasta, but it feels a little strained.",
  "A mushroom walks into a bar. The bartender says, 'We don't serve your kind here.' The mushroom replies, 'Why not? I'm a fungi!'",
  "Kitchen Confession: I tried to have a serious talk with the fish, but it is swimming upstream.",
  "You know it's a bad dinner service when the line cook looks at you and says, 'Well, at least it's cooked... mostly.'",
  "You know you're an adult when you have a favorite stove burner. Bottom right, ride or die.",
  "Overheard in the back of house: The waiter just forgot to salt the pasta water. We are officially doomed.",
  "Kitchen Confession: I tried to have a serious talk with the cookie, but it is feeling crummy.",
  "Kitchen Confession: I tried to have a serious talk with the pie, but it is acting crusty.",
  "Kitchen Confession: I tried to have a serious talk with the steak, but it is rare to find.",
  "Overheard in the back of house: The line cook just ate half the inventory. We are officially doomed.",
  "Never trust an oven on a Monday. It's usually baked.",
  "Kitchen Confession: I tried to have a serious talk with the carrot, but it has deep roots.",
  "Overheard in the back of house: The bartender just tried to deglaze a pan with tap water. We are officially doomed.",
  "I think my blender is passive aggressive. It's always a smooth operator.",
  "The worst thing about working in a restaurant? You can't make a mistake without someone roasting you for it.",
  "Kitchen Confession: I tried to have a serious talk with the milk, but it is past its prime.",
  "People who love to eat are always the best people. Except when they eat my leftovers.",
  "Kitchen Confession: I tried to have a serious talk with the soup, but it is boiling mad.",
  "Overheard in the back of house: The sous chef just yelled at the host. We are officially doomed.",
  "I think my toaster is passive aggressive. It's always popping off.",
  "A good chef is just a chemist who gets to eat their experiments.",
  "Kitchen Confession: I tried to have a serious talk with the cake, but it is frosting my patience.",
  "Kitchen Confession: I tried to have a serious talk with the onion, but it has too many layers.",
  "Roommate ad: Must be okay with my sink. It can be a little plugged in at times.",
  "Overheard in the back of house: The head chef just dropped the prime rib. We are officially doomed.",
  "I don't need a recipe, I just measure garlic with my heart.",
  "I asked the butcher for a cut of beef. He said, 'The stakes are high.'",
  "Kitchen Confession: I tried to have a serious talk with the water, but it is feeling tapped out.",
  "I think my coffee maker is passive aggressive. It's always brewing up schemes.",
  "You know it's a bad dinner service when the dishwasher looks at you and says, 'Well, at least it's cooked... mostly.'",
  "I think my sink is passive aggressive. It's always draining my energy.",
  "Overheard in the back of house: The restaurant owner just tried to deglaze a pan with tap water. We are officially doomed.",
  "I tried to make a belt out of watches, but it was a waist of thyme.",
  "I asked the waiter if the chef cooks with love. He said, 'No, mostly just butter and rage.'",
  "Nothing unites a kitchen staff quite like a printer that won't stop spitting out tickets.",
  "The hardest part of baking isn't the measurements. It's waiting for the butter to soften without microwaving it into a puddle.",
  "You haven't known true panic until you realize you're out of vanilla extract halfway through a recipe.",
  "A perfectly clean kitchen is a sign of a wasted life... or just someone who ordered takeout.",
];
