/**
 * A standalone bank of kitchen/cooking one-liners -- distinct from
 * ChefSprite/ChefSprite3D's own DEFAULT_LINES (which are in-character banter
 * about the chef's session/rendering/idle state). This is just actual jokes,
 * meant to be passed as `lines` to ChefMascot wherever a caller wants the
 * chef telling jokes instead of doing his usual bit. 300 unique lines.
 */
export const KITCHEN_JOKES: string[] = [
  "Why did the tomato turn red? It saw the salad dressing.",
  "I'm on a seafood diet. I see food, and I eat it.",
  "Why don't eggs tell jokes? They'd crack each other up.",
  "What do you call a sad strawberry? A blueberry.",
  "I burned a candle down the middle. Now I've got double the wax.",
  "What do you call cheese that isn't yours? Nacho cheese.",
  "Why did the cookie go to the doctor? It was feeling crummy.",
  "What did the lettuce say to the celery? Quit stalking me.",
  "Why did the chef quit? He lost his thyme.",
  "What's a chef's favorite kind of music? Sax and the city.",
  "Why don't chefs ever get cold? They stand near the whisk.",
  "What do you call a fake noodle? An impasta.",
  "Why did the banana go to the doctor? It wasn't peeling well.",
  "What's a pepper's favorite exercise? Jalapeno business squats.",
  "Why did the mushroom get invited to every party? He's a fungi.",
  "What do you call an egg from outer space? An egg-stra terrestrial.",
  "Why do chefs make terrible comedians? Their jokes are too corny.",
  "What did the grape say when it got stepped on? Nothing, it just let out a little wine.",
  "Why did the baker stop making bread? He kneaded a break.",
  "What do you call a nervous vegetable? A rattled radish.",
  "Why did the pasta get sent to the principal's office? It couldn't stop being saucy.",
  "What's the most patient vegetable in the kitchen? The waiting turnip.",
  "Why did the sandwich stop telling jokes? The bread was getting stale.",
  "What do you call a lazy kangaroo chef? Pouch potato.",
  "Why did the orange stop rolling? It ran out of juice.",
  "What's a chef's favorite type of ship? A pantryship.",
  "Why did the potato win the argument? It had a lot of good points.",
  "What do you call a dog that cooks? A pot-hound.",
  "Why did the tomato blush at the salad bar? It saw the dressing.",
  "What's a chef's favorite way to relax? Just let it stew.",
  "Why did the onion win the award? It made everyone cry tears of joy.",
  "What do you call a pig that cooks? A ham chef.",
  "Why did the egg refuse to fight? It didn't want to get scrambled.",
  "What's the chef's favorite kind of math? Pie charts.",
  "Why did the broccoli break up with the cauliflower? It found someone greener.",
  "What do you call a chef who's always calm? Un-fry-ttled.",
  "Why did the cookbook look sad? It had too many bland pages.",
  "What's a chef's favorite instrument? The pan-flute.",
  "Why did the carrot blush? It saw the salad dressing again.",
  "What do you call a sleepy dessert? A napoleon.",
  "Why did the chef bring a ladder to work? To reach the high notes in the soup.",
  "What's a fish's favorite kitchen tool? The scale.",
  "Why did the pancake stop the fight? It didn't want any more batter.",
  "What do you call a chef who tells dad jokes? Pun-gent.",
  "Why did the salt and pepper break up? They stopped seasoning eye to eye.",
  "What's a chef's favorite kind of story? One with a good plot twist, served al dente.",
  "Why did the bread go to therapy? It had too many crumby thoughts.",
  "What do you call a very small chef? A mini-chef d'oeuvre.",
  "Why did the soup apologize? It was feeling a little souperficial.",
  "What's a chef's least favorite dance? The souffle-shuffle, it always falls flat.",
  "Why did the waffle get promoted? It really knew how to grid its teeth and work.",
  "What do you call a chef who works out? A gym-nast-urtium.",
  "Why did the recipe break up with the oven? It needed more space.",
  "What's a chef's favorite kind of humor? Anything with good seasoning.",
  "Why did the spoon marry the fork? They just clicked at the dinner table.",
  "What do you call a chef who's always late? Behind schedule, but ahead of thyme.",
  "Why did the cake feel lonely? It was the only one at the party with layers.",
  "What's a chef's favorite type of exercise? Whisking away the calories.",
  "Why did the noodle apply for a job? It wanted to work its way up.",
  "What do you call a chef who tells the truth? A whole-wheat honest type.",
  "Why did the garlic get a promotion? It really knew how to clove its way up.",
  "What's a chef's favorite kind of vacation? Anywhere with good thyme off.",
  "Why did the chef break up with the calendar? Too many dates.",
  "What do you call a fish that's great at cooking? A sole chef.",
  "Why did the pot feel proud? It finally found its lid.",
  "What's a chef's favorite kind of workout? Deadlifting the stockpot.",
  "Why did the flour go quiet? It didn't want to spill the batter.",
  "What do you call a chef who never stops talking? A whisk-taker.",
  "Why did the cabbage always win at poker? It had a lot of leaves up its sleeve.",
  "What's a chef's favorite kind of movie? Anything with a good plot and a better crust.",
  "Why did the recipe get famous? It had all the right ingredients for success.",
  "What do you call a chef who loves the beach? A grill-master with sandy toes.",
  "Why did the cucumber apply to be a comedian? It was naturally pickled with humor.",
  "What's a chef's favorite kind of party game? Musical chairs, but with cutting boards.",
  "Why did the steak refuse to fight? It didn't want to get grilled.",
  "What do you call a chef who's obsessed with grains? A rice enthusiast, obviously.",
  "Why did the avocado go to school? It wanted to become a smarter smash.",
  "What's a chef's favorite kind of mystery? Whodunit, but with a side of whodunit.",
  "Why did the pie feel embarrassed? Everyone kept talking about its crust.",
  "What do you call a chef who loves puns? A seasoned professional.",
  "Why did the celery get promoted? It always stayed crunchy under pressure.",
  "What's a chef's favorite kind of school subject? Home ec, obviously, but also thermo-dynamics.",
  "Why did the yeast feel important? Without it, nothing would rise to the occasion.",
  "What do you call a chef who loves horror movies? A fan of things that go bump in the kitchen.",
  "Why did the sauce get invited everywhere? It really knew how to bring people together.",
  "What's a chef's favorite kind of weather? Anything that doesn't wilt the lettuce.",
  "Why did the toast feel confident? It always landed butter side up, eventually.",
  "What do you call a chef who's great at multitasking? A whisk manager.",
  "Why did the recipe book feel proud? It finally got a good binding review.",
  "What's a chef's favorite kind of car? Anything with good mileage on the stovetop.",
  "Why did the herbs get along so well? They were naturally well-seasoned together.",
  "What do you call a chef who loves the ocean? A saltwater seasoning specialist.",
  "Why did the batter feel nervous? It was about to get whisked into something big.",
  "What's a chef's favorite kind of holiday? Any day that ends in pie.",
  "Why did the knife feel sharp today? It had a really good night's rest on the block.",
  "What do you call a chef who's always positive? A silver-lining sous chef.",
  "Why did the stove feel appreciated? Everyone always came back to it in the end.",
  "What's a chef's favorite kind of joke? One that's well-baked and never half-cooked.",
  "Why did the recipe get an award? It really knew how to bring the heat.",
  "What do you call a chef who loves puzzles? A seasoning strategist.",
  "Why did the pot of soup feel relaxed? It was finally simmering down.",
  "What's a chef's favorite kind of sport? Anything involving a good whisking motion.",
  "Why did the bread feel confident walking into the oven? It knew it would rise to the occasion.",
  "What do you call a chef who loves math? Someone who really knows their fractions of a cup.",
  "Why did the spice rack feel organized? Everything was finally in its right place, seasoned to perfection.",
  "What's a chef's favorite kind of dance move? The sizzle and shimmy.",
  "Why did the recipe feel nostalgic? It had been passed down through generations of good seasoning.",
  "What do you call a chef who loves gardening? A herb enthusiast with a green thumb and a sharp knife.",
  "Why did the kitchen towel feel useful? It really knew how to wipe out any mess.",
  "What's a chef's favorite kind of riddle? One that takes just the right amount of thyme to solve.",
  "Why did the cutting board feel confident? It had seen it all, chopped it all, survived it all.",
  "What do you call a chef who tells the best stories? A seasoned storyteller with great timing.",
  "Why did the recipe feel loved? Everyone kept coming back for seconds.",
  "What's a chef's favorite kind of game night? Anything that ends with a good roast.",
  "Why did the whisk feel accomplished? It finally got everything all mixed up in a good way.",
  "What do you call a chef who's always calm under pressure? A steady hand at the stove.",
  "Why did the recipe feel confident about its future? It had all the right ingredients lined up.",
  "What's a chef's favorite kind of comedy? Anything with really good timing and a great punchline.",
  "Why did the oven mitt feel important? Without it, things could get pretty heated.",
  "What do you call a chef who loves history? Someone who really respects the classics, seasoned to taste.",
  "Why did the recipe card feel proud? It finally got framed on the wall of fame.",
  "What's a chef's favorite kind of adventure? Anything that starts with a good mise en place.",
  "Why did the spatula feel confident? It always knew how to flip a bad situation around.",
  "What do you call a chef who loves music? Someone who really knows how to whisk to the beat.",
  "Why did the recipe feel accomplished? It finally nailed the perfect balance of flavors.",
  "What's a chef's favorite kind of vacation spot? Anywhere with a great local market and fresh herbs.",
  "Why did the ladle feel useful? It always knew how to dish out exactly what was needed.",
  "What do you call a chef who loves puzzles and riddles? A seasoning connoisseur with a sharp mind.",
  "Why did the recipe feel triumphant? It finally got the timing just right, down to the last second.",
  "What's a chef's favorite kind of celebration? Anything that ends with a well-deserved feast.",
  "Why did the mixing bowl feel important? Everything came together because of it.",
  "What do you call a chef who loves teamwork? Someone who really knows how to whisk together a great crew.",
  "Why did the recipe feel confident walking into the kitchen? It had been tested and perfected many times over.",
  "What's a chef's favorite kind of weekend plan? Anything involving a slow-cooked masterpiece.",
  "Why did the timer feel important? Without it, everything would either be undercooked or burnt.",
  "What do you call a chef who loves a good challenge? Someone who thrives under the heat of the moment.",
  "Why did the recipe feel like a masterpiece? It finally balanced sweet, salty, and everything in between.",
  "What's a chef's favorite kind of friendship? One that's well-seasoned and stands the test of time.",
  "Why did the apron feel proud? It had survived every splatter and spill with dignity.",
  "What do you call a chef who loves a good debate? Someone who really knows how to season an argument.",
  "Why did the recipe feel victorious? It finally got the crowd's approval after several taste tests.",
  "What's a chef's favorite kind of night out? Anything that ends with a well-plated dessert.",
  "Why did the tongs feel confident? They always knew how to grab the moment.",
  "What do you call a chef who loves storytelling around the table? A seasoned narrator with great pacing.",
  "Why did the recipe feel complete? Every ingredient finally found its perfect place.",
  "What's a chef's favorite kind of morning routine? One that starts with the smell of fresh bread.",
  "Why did the colander feel useful? It always knew how to strain out the unnecessary.",
  "What do you call a chef who loves a fresh start? Someone who really knows how to clean the slate, and the counter.",
  "Why did the recipe feel like a legend? It had been shared, tweaked, and loved by so many.",
  "What's a chef's favorite kind of encouragement? A good seasoning of positive feedback.",
  "Why did the rolling pin feel confident? It always knew how to smooth things out.",
  "What do you call a chef who loves a bit of drama? Someone who really knows how to season a good plot twist.",
  "Why did the recipe feel unstoppable? It had survived every kitchen disaster and come out better each time.",
  "What's a chef's favorite kind of teamwork exercise? Passing the salt, literally and figuratively.",
  "Why did the grater feel important? It always knew how to shred the tension in the room.",
  "What do you call a chef who loves a fresh perspective? Someone who really knows how to season things differently.",
  "Why did the recipe feel timeless? It never went out of style, no matter the decade.",
  "What's a chef's favorite kind of pep talk? One that reminds everyone they're the secret ingredient.",
  "Why did the measuring cup feel confident? It always knew exactly how much was needed.",
  "What do you call a chef who loves precision? Someone who really knows how to level off a good measurement.",
  "Why did the recipe feel proud of its journey? It started as a rough draft and became a masterpiece.",
  "What's a chef's favorite kind of surprise? A dish that turns out even better than expected.",
  "Why did the strainer feel accomplished? It always knew how to separate the good from the excess.",
  "What do you call a chef who loves a slow burn? Someone who really appreciates a good simmer.",
  "Why did the recipe feel confident about criticism? It knew feedback only made it better.",
  "What's a chef's favorite kind of celebration meal? One that brings everyone together at the table.",
  "Why did the peeler feel useful? It always knew how to get straight to the good stuff.",
  "What do you call a chef who loves a fresh challenge? Someone who really thrives when the heat is on.",
  "Why did the recipe feel legendary? It had been perfected through trial, error, and a lot of love.",
  "What's a chef's favorite kind of quiet moment? The calm right before the dinner rush.",
  "Why did the whisk feel like a hero? It turned chaos into something smooth and delicious.",
  "What do you call a chef who loves a fresh batch? Someone who really believes in second chances, and thirds.",
  "Why did the recipe feel confident on opening night? It had been rehearsed to perfection.",
  "What's a chef's favorite kind of encouragement to a nervous cook? Just trust the process, it'll simmer down.",
  "Why did the pan feel proud? It handled the heat and came out shining.",
  "What do you call a chef who loves a good comeback story? Someone who really appreciates a dish that rises again.",
  "Why did the recipe feel unbreakable? It had survived every substitution and still tasted great.",
  "What's a chef's favorite kind of teamwork lesson? Everyone brings their own flavor to the table.",
  "Why did the spice jar feel important? A little of it went a long way.",
  "What do you call a chef who loves patience? Someone who really understands that good things take time to marinate.",
  "Why did the recipe feel confident before the big review? It knew every step had been tested.",
  "What's a chef's favorite kind of reminder? Even the best dishes need a little seasoning to shine.",
  "Why did the cutting board feel wise? It had seen every kind of chop and come out unscathed.",
  "What do you call a chef who loves a fresh outlook? Someone who really knows how to plate things differently.",
  "Why did the recipe feel confident under pressure? It had been through the fire, literally, and thrived.",
  "What's a chef's favorite kind of life lesson? Sometimes you just have to let it simmer and trust the process.",
  "Why did the oven feel appreciated? It turned raw potential into something truly special.",
  "What do you call a chef who loves a good origin story? Someone who really respects where a recipe began.",
  "Why did the recipe feel confident facing critics? It knew its flavor spoke for itself.",
  "What's a chef's favorite kind of motivational quote? Season boldly, taste often, never stop stirring.",
  "Why did the fork feel needed? Every great dish deserves a proper introduction.",
  "What do you call a chef who loves a fresh start every morning? Someone who really believes in a clean prep station.",
  "Why did the recipe feel timeless and beloved? It brought people together, one bite at a time.",
  "What's a chef's favorite kind of closing thought? The best meals are the ones shared, not just cooked.",
  "Why did the pot feel confident about its contents? It knew good things take time to come together.",
  "What do you call a chef who loves the little details? Someone who really believes garnish matters.",
  "Why did the recipe feel proud walking off the stove? It knew it had given its absolute best.",
  "What's a chef's favorite kind of send-off? Bon appetit, and don't forget the leftovers.",
  "Why did the salt shaker feel confident? It knew exactly how to bring out the best in everything.",
  "What do you call a chef who loves a fresh challenge every single day? Someone who really believes the kitchen never gets boring.",
  "Why did the recipe feel like a triumph? It turned a handful of ingredients into something unforgettable.",
  "What's a chef's favorite kind of farewell? Until next time, keep the pot simmering.",
  "Why did the frying pan feel like a champion? It handled the heat and still came out golden.",
  "What do you call a chef who loves a fresh twist on tradition? Someone who really respects the classics while adding their own flair.",
  "Why did the recipe feel confident about its legacy? It knew it would be passed down for generations.",
  "What's a chef's favorite kind of final thought? Every dish tells a story, make yours a good one.",
  "Why did the mixing spoon feel accomplished? It brought everything together into one delicious whole.",
  "What do you call a chef who loves a good finishing touch? Someone who really believes presentation is half the meal.",
  "Why did the recipe feel confident stepping into the spotlight? It had been tested, tasted, and truly perfected.",
  "What's a chef's favorite kind of goodbye? Keep the kitchen warm, I'll be back for seconds.",
  "Why did the chef bring a map to the kitchen? He kept losing his thyme and needed directions.",
  "What do you call two chefs arguing over a recipe? A culinary standoff, seasoned with tension.",
  "Why did the vegetable garden feel proud? Every single plant had really grown into its role.",
  "What's a chef's favorite kind of workout plan? Lifting stockpots and calling it cardio.",
  "Why did the sauce feel confident at the tasting? It knew it had the perfect balance of flavors.",
  "What do you call a chef who loves teaching? Someone who really believes every mistake is a seasoning lesson.",
  "Why did the recipe feel calm before the big dinner? It trusted every step it had already perfected.",
  "What's a chef's favorite kind of reward? A clean plate and a happy table.",
  "Why did the knife block feel organized? Everything finally had its proper place, sharp and ready.",
  "What do you call a chef who loves a fresh perspective on old recipes? Someone who really respects tradition while stirring in something new.",
  "Why did the recipe feel triumphant after years of tweaking? It finally became the dish everyone requested by name.",
  "What's a chef's favorite kind of quiet confidence? Knowing the dish will speak for itself.",
  "Why did the pot lid feel important? Without it, all that good flavor would just float away.",
  "What do you call a chef who loves a fresh new menu? Someone who really believes variety keeps things interesting.",
  "Why did the recipe feel unshakeable after a bad review? It knew not every palate agrees, and that's fine.",
  "What's a chef's favorite kind of morning ritual? The first sip of coffee before the first prep of the day.",
  "Why did the whisk feel like an old friend? It had been there through every batter and every breakthrough.",
  "What do you call a chef who loves a good challenge on a busy night? Someone who really thrives when the tickets pile up.",
  "Why did the recipe feel confident despite the chaos? It knew good cooking often comes from controlled chaos.",
  "What's a chef's favorite kind of teamwork moment? When everyone moves like clockwork during the dinner rush.",
  "Why did the cutting board feel like a trusted partner? It had held steady through every single prep.",
  "What do you call a chef who loves the quiet after closing? Someone who really appreciates a clean, finished kitchen.",
  "Why did the recipe feel proud of its simplicity? Sometimes the best dishes just need a few honest ingredients.",
  "What's a chef's favorite kind of celebration after a long shift? Sitting down and finally eating something themselves.",
  "Why did the stove feel like a reliable friend? It never let the chef down, heat after heat.",
  "What do you call a chef who loves the smell of fresh bread? Someone who really believes mornings start in the oven.",
  "Why did the recipe feel confident heading into a competition? It had been refined through countless late nights.",
  "What's a chef's favorite kind of quiet victory? A dish coming out exactly as imagined.",
  "Why did the apron feel like armor? It protected against every splash and every spill of the shift.",
  "What do you call a chef who loves the first taste test? Someone who really believes the proof is in the tasting.",
  "Why did the recipe feel like home? It reminded everyone of family dinners long past.",
  "What's a chef's favorite kind of encouragement to a new hire? Trust your hands, they'll learn the rhythm.",
  "Why did the timer feel like a trusted guide? It always knew exactly when the moment was right.",
  "What do you call a chef who loves the hum of a busy kitchen? Someone who really thrives in the organized chaos.",
  "Why did the recipe feel confident despite substitutions? It knew flexibility was part of good cooking.",
  "What's a chef's favorite kind of quiet pride? Watching someone enjoy a dish without knowing who made it.",
  "Why did the pan feel seasoned in more ways than one? Years of use had made it wiser and better.",
  "What do you call a chef who loves teaching new techniques? Someone who really believes knowledge tastes better shared.",
  "Why did the recipe feel confident on a slow night? It knew quality mattered more than quantity.",
  "What's a chef's favorite kind of small joy? The smell of onions caramelizing just right.",
  "Why did the spoon feel like a trusted companion? It had stirred through victories and mishaps alike.",
  "What do you call a chef who loves the calm before service? Someone who really values the quiet prep before the storm.",
  "Why did the recipe feel confident despite a tough crowd? It knew good food eventually wins everyone over.",
  "What's a chef's favorite kind of legacy? A recipe that gets requested for years to come.",
  "Why did the oven mitt feel like a quiet hero? It protected against the heat nobody else noticed.",
  "What do you call a chef who loves the first bite of a new dish? Someone who really believes that moment tells the whole truth.",
  "Why did the recipe feel like a warm welcome? It reminded everyone that good food is really about good company.",
  "What's a chef's favorite kind of closing line for the night? Lights off, stove cool, see you tomorrow.",
  "Why did the chicken cross the kitchen? To get to the other stovetop.",
  "What do you call a chef who's afraid of the deep fryer? A little battered.",
  "Why did the recipe refuse to argue? It didn't want things to boil over.",
  "What's a chef's favorite kind of magic trick? Turning leftovers into a whole new meal.",
  "Why did the sugar feel sweet on the inside? It was just being true to itself.",
  "What do you call a chef who's great under pressure? A pressure-cooker professional.",
  "Why did the recipe blush at the compliment? It wasn't used to being buttered up.",
  "What's a chef's favorite kind of pun? Anything that's well done, medium rare in delivery.",
  "Why did the whisk get a standing ovation? It really beat the competition.",
  "What do you call a chef who's always punctual? Right on the dot, like a good sauce reduction.",
  "Why did the recipe feel like royalty? Everyone bowed down to its flavor.",
  "What's a chef's favorite kind of bedtime story? One with a satisfying, well-cooked ending.",
  "Why did the garlic press feel powerful? It really knew how to crush the competition.",
  "What do you call a chef who loves symmetry? Someone who really believes in even plating.",
  "Why did the recipe feel confident in a taste test? It had nothing to hide, just good flavor.",
  "What's a chef's favorite kind of exercise class? Kneading dough, twice a week.",
  "Why did the blender feel unstoppable? It could smooth over any situation.",
  "What do you call a chef who loves a fresh challenge each shift? Someone who really thrives on variety.",
  "Why did the recipe feel proud after a rewrite? It finally found its true flavor.",
  "What's a chef's favorite kind of pep talk before a big order? Just breathe, and don't forget the garnish.",
  "Why did the steak knife feel confident? It always knew how to cut right to the point.",
  "What do you call a chef who loves a well-organized pantry? Someone who really believes labels save lives.",
  "Why did the recipe feel unstoppable after years of practice? Muscle memory and good seasoning.",
  "What's a chef's favorite kind of Friday night? One with a full dining room and an empty stress list.",
  "Why did the mixing bowl feel like a good listener? It held everything together without judgment.",
  "What do you call a chef who loves a quiet Sunday prep? Someone who really believes in getting ahead of the week.",
  "Why did the recipe feel confident at the family table? It knew home cooking always wins hearts.",
  "What's a chef's favorite kind of teamwork story? One where everyone plates together at the pass.",
  "Why did the cutting knife feel sharp and ready? A good night's rest on the whetstone never hurts.",
  "What do you call a chef who loves the first frost of fall? Someone who really believes soup season has arrived.",
  "Why did the recipe feel confident walking into a food critic's review? It had nothing to prove, just good flavor to share.",
  "What's a chef's favorite kind of quiet confidence booster? A perfectly reduced sauce that needs no adjusting.",
  "Why did the spatula feel like an old reliable friend? It never once let a pancake down.",
  "What do you call a chef who loves the smell of fresh basil? Someone who really believes herbs make the dish sing.",
  "Why did the recipe feel confident before a holiday feast? It had been perfected over many family gatherings.",
  "What's a chef's favorite kind of quiet triumph? A soufflé that didn't fall.",
  "Why did the ladle feel proud serving the soup? It knew every bowl mattered just as much as the last.",
  "What do you call a chef who loves the first day of a new menu? Someone who really believes in fresh starts.",
  "Why did the recipe feel confident despite a kitchen mishap? It knew every great dish survives a few bumps along the way.",
  "What's a chef's favorite kind of quiet gratitude? A full table and an empty plate.",
  "Why did the oven feel like a trusted companion through the years? It turned every hope into something real, one dish at a time.",
  "Why did the chef refuse to share the secret recipe? Some things just need to stay in the family, whisked away.",
];
